---
- hosts: localhost
  vars:
    OSP_GUID: 9911
  tasks:
  - name: Create workstation inventory
    add_host:
       name: "workstation-{{OSP_GUID}}.rhpds.opentlc.com"
       group: workstation

- hosts: workstation
  become: yes
  roles:
    - osp-facts

- name: Base Configuration
  hosts: all
  gather_facts: true
  become: true
  roles:
    - role: base-config

- name: Deploy haproxy
  hosts: frontends
  become: true
  roles:
    - role: haproxy

- name: Deploy Tomcat
  hosts: apps
  become: true
  roles:
    - role: tomcat

- name: Deploy PostgreSQL
  hosts: appdbs
  become: true
  roles:
    - role: geerlingguy.postgresql
      become: yes
